### ISSUE TITLE
Doktypes and default Page Layout

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidpages#218]
Hi there,
I'm trying for two days to do this work

```
[page|doktype = 70]
    TCAdefaults.pages.tx_fed_page_controller_action=m8thlayout->Layout
[GLOBAL]
```

If I only use

```
TCAdefaults.pages.tx_fed_page_controller_action=m8thlayout->Layout
```

Without the conditional block, all new pages are getting the default value.
I was debbuging ConditionMatcher and the condition is working fine.

The goal is to be able to drag and drop to the page tree different doktypes and set a different default Page Layout for each of them.

Could anyone bring me some help with this? Did anyone tried something similar?

Regards,

**Comment by MaxGTR** [comment]
No solution for this problem ?

**Comment by cedricziel** [comment]
Hi @MaxGTR, you're answering to an issue that's 2 yrs old. Please open an issue describing the steps you took and what you expect / what problem you're trying to solve. Thx!
