### ISSUE TITLE
Copied localised Content Elements has always colPos = 0 after paste

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/fluidpages#219]
Copy a content element (which have localised versions) from Column (colPos = 0)
Paste into Column with colPos 1
After paste the copied localised content elements have always colPos = 0

**Comment by NamelessCoder** [comment]
@glucka Are you closing this because it no longer is an issue? Is the problem gone from your install or did you identify the cause as something outside FluidTYPO3?

**Comment by glucka** [comment]
still is an issue, i wanted to report to flux package today

**Comment by NamelessCoder** [comment]
Ah, ok - thanks :) Yes, this one should be reported to Flux since it's most likely an issue there.

**Comment by glucka** [comment]
ok
