### ISSUE TITLE
Error when installing fluidpages in TYPO3 7.1 on unix/linux

### ISSUE THREAD

**Issue by randomresult** [FluidTYPO3/fluidpages#220]
i get an error installing T3 7.1 and the latest Extensions. 
I did the following: 
initialised empty Git-Repo
added Submodule T3 into folder typo3_src (commit 0065134fc402bb1570f6dd46175f9e42a16c9846)
added Submodule for flux (commit aae6bce807e175fedbc59a0ea5916d92d90ff23e)
added Submodule for fluidpages (commit b55827964163dacd24081595e34a89d35bb196c8)
added Submodule for fluidcontent (commit c79563326524138fd41cccfdc9ca7ba51714b351)
added Submodule for vhs (commit feec8a1c570b21166049e6c1bc9fb9656aaa5729)

Enabled installtool 
Run the installtool 
installed extensions using extmanager
created page 
created TS template
(
# Default PAGE object:
page = PAGE
page.10 = TEXT
page.10.value = HELLO WORLD!
) 

Got an error in Frontend. 
 Oops, an error occurred! Code: 201501032250268cfbcc2aHELLO WORLD! 
(Blank white page with this error)

Uninstalled fluidpages 
Cleared Cache (arrow / not installtool) 
no error in frontend - only HELLO WORLD 

This happens on a Mittwald-Server

Did the same on Windows and Mac - Works without problem. 

Any hints on this?

**Comment by xf-** [comment]
backtrace everything - works fine on my VM

**Comment by xf-** [comment]
https://github.com/FluidTYPO3/vhs/pull/750 solved it.
I think was something with dev core and fixed and 750 was a new error.
