### ISSUE TITLE
fluidpages is not working in TYPO3 7.0.3

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidpages#227]
Hi there,

I have a fresh installation made with FluidTYPO3-Vagrant with CMS 7.0.3 and development repositories of FluidTYPO3. When I create my provider extension, and I go to my root page to select a page layout, page layout appears, I click in one of them to select it but when I save, it is not selected.

I tried with compatibility mode and without it. I tried with automatic initialization of fluidpages and without it.

I executed update scripts, the result is the same. I'm not getting errors.

Regards

**Comment by jmverges** [comment]
![issue](https://cloud.githubusercontent.com/assets/2902073/6486071/a2a9fb2c-c288-11e4-80b7-5df6d2b772ca.png)

I'm also getting a weird behaviour on 6.2.10 and 6.2.11 with fluidpages development version

**Comment by NamelessCoder** [comment]
You may need an SQL schema update - or your SQL daemon may be configured to expect complete inserts when fields have no default values. If it is the complete inserts thing: traditionally this happens on MySQL 5.6 when using the default configuration and removing strict mode usually solves it right away.

**Comment by jmverges** [comment]
My database version:
Server version: 10.1.3-MariaDB-1~wheezy-wsrep mariadb.org binary distribution, wsrep_25.10.r4144

output of SELECT @@GLOBAL.sql_mode


+-------------------+
| @@GLOBAL.sql_mode |
+-------------------+
|                   |
+-------------------+
1 row in set (0.00 sec)

**Comment by NamelessCoder** [comment]
Please recheck and close if fixed.

**Comment by jmverges** [comment]
I moved to CMS 6.2.10 and master branch for all FluidTYPO3 extensions. Now I'm experimenting an other weird behaviour. I can see into the database this:

![image](https://cloud.githubusercontent.com/assets/2902073/6622635/16cca2a6-c8de-11e4-9988-18a5a89d2c22.png)

If I go to Page Layouts it is fine:
![image](https://cloud.githubusercontent.com/assets/2902073/6622664/4fa6a478-c8de-11e4-8fc1-b182b4140487.png)
I'm also getting the expecting output in Page Configuration and also in FE

The weird fact is that I'm not able to see the expected result it in Web->Page
![image](https://cloud.githubusercontent.com/assets/2902073/6622694/8e4a57ce-c8de-11e4-8e18-c48cf602b0b0.png)

I tried to change manually some pages under root pid first and then I changed the page layout in the root page and I'm getting always the same option.

Any clue?

**Comment by jmverges** [comment]
Maybe I should open a different issue. In the root page I'm able to change the Page Layout of the current page changing the Page Layout - subpages
In the subpages I'm not able to modify the layout showed in Page->Web

**Comment by NamelessCoder** [comment]
I'm unable to reproduce this one - I'm pretty sure it is fixed or that some setting in the site is causing the layout to be ignored, inherited unexpectedly, etc.

I've checked this on a 6.2 and 7.1 (since 7.0 is discontinued) and both appear to be in working order.

If you do come closer to an explanation don't be afraid to open a new issue ;) but we won't be spending efforts to make 7.0-specific fixes, given that this version is no longer officially supported from TYPO3.
