### ISSUE TITLE
FluidTYPO3\Fluidpages\Provider\PageProvider::getInheritanceTree() must be public

### ISSUE THREAD

**Issue by seabass86** [FluidTYPO3/fluidpages#230]
Extension throws the following error, if Automatic initialisation is set to FALSE, no provider extension is installed yet and I try to go to  a page in the Page Module that has a traditional Typo3 Template and content elements on it already. 

Fatal error: Access level to FluidTYPO3\Fluidpages\Provider\PageProvider::getInheritanceTree() must be public (as in class FluidTYPO3\Flux\Provider\AbstractProvider) in /typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php on line 34

**Comment by NamelessCoder** [comment]
Sounds like your repositories are out of sync. If you use development of fluidpages you must also use development of flux. And I think the problem in your case can be fixed by pulling the most recent changes from flux.
