### ISSUE TITLE
[DOC] RSS configuration?

### ISSUE THREAD

**Issue by zelcode** [FluidTYPO3/fluidpages#233]
Hi @NamelessCoder,

could you, please, share your RSS setup on http://fluidtypo3.org/feed.rss, what should go in template and layout files, and if any special typoscript.

Thanks!

**Comment by NamelessCoder** [comment]
Sure - see https://github.com/FluidTYPO3/fluidtypo3org/blob/development/Configuration/TypoScript/setup.txt#L122

**Comment by zelcode** [comment]
Thanks for help, but can't get it, all I get is XML error on first line. Searching more found this solution:

http://www.wapplersystems.de/blog/typo3-rss-feed-fuer-news-extension/

which works in my case (only `format = xml`), don't know is it right solution. If I try `format = atom` there is only RSS header with empty page, but interesting in source code everything seems fine, all news are there, only not displayed.
(news 3.1.0)
