### ISSUE TITLE
New fluidpages development version doesn't work anymore for creating pages

### ISSUE THREAD

**Issue by Madii** [FluidTYPO3/fluidpages#235]
HI,

i used the FluidTYPO3-Vagrant VM and installed various versions of Typo3 (6.2,7.0,7.1) . I always get the following error if i try to create a new page:

`PHP Catchable Fatal Error: Argument 1 passed to FluidTYPO3\Fluidpages\Provider\PageProvider::getForm() must be of the type array, null given, called in /var/www/typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php on line 228 and defined in /var/www/typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php line 157`

**Comment by Madii** [comment]
I dont't know if it helps. I see you are using now the `RecordService.php` of Flux. After some bugtracing it is obvious why an error comes, cause the DB query doesn't make sense.
Why is even the method `postProcessRecord` in `PageProvider` called when i create a page? 
The query that is made is for 
````php
$table = 'page', $fields = '*', $uid = 'NEW12345'. 
````
And with `intval($uid) comes out $uid = 0.
The only record i have is the one which comes with installation. 

If i see it right the solution for this bug can be found in fluidcontent_core where this method is called.

**Comment by NamelessCoder** [comment]
Thanks Gregor - fixed!
