### ISSUE TITLE
"Page Configuration - subpages" overwrites "Page Configuration" in fluidpages 3.2.0

### ISSUE THREAD

**Issue by jenses** [FluidTYPO3/fluidpages#238]
weiter auf deutsch, sonst wird das nix :-(

Nach dem Update von fluidpages auf 3.2.0 werden sämtliche Konfigurationen aus "Page Configuration" ignoriert,
stattdessen werden grundsätzlich die Werte aus "Page Configuration - subpages" ausgelesen und im FE benutzt.
Sämtliche andere Extensions von fluidTYPO3 wurden gleichzeitig auch auf den neuesten Stand gebracht.
Das würde ich als "Blocker" bezeichnen.

**Comment by jenses** [comment]
Ergänzung:
dieser Fehler tritt nur auf, wenn bei "Page Layout - this page" "Parent decides " gewühlt wurde,
wird stattdessen irgendein Page Template ausgewählt,
wird "Page Configuration" ausgewertet.
Vor dem Update wurde "Page Configuration" grundsätzlich ausgewertet...

**Comment by xf-** [comment]
confirmed

**Comment by xf-** [comment]
Duplicate of https://github.com/FluidTYPO3/fluidpages/issues/239
Please report in English.
