### ISSUE TITLE
Tab "Page - Configuration" is always empty

### ISSUE THREAD

**Issue by Madii** [FluidTYPO3/fluidpages#240]
I don't get it...i am using Typo3 7.1 and it doesn't matter if i use fluidbootstraptheme or the site extension. The configuration tab is always empty. I think this shouldn't be right? :-)

**Comment by Outdoorsman** [comment]
You might play with the extension configuration checkboxes in fluidbootstraptheme, run all the update scripts for the FluidTYPO3 extensions and force clear all cache.

Probably doesn't answer the questions, but at least for the next little bit, you might also want to try using v2.0 branch of fluidbootstraptheme until it's merged... it's a little more recent code, though not fully tested.

**Comment by Madii** [comment]
Thx man. You are right. v2.0 did the trick in fluidbootstraptheme. So still the site extension here needs some updates to work in typo3 7.1 :)

**Comment by NamelessCoder** [comment]
@Madii am I right in assuming this one can then be closed, fixed by the upgrade of fluidbootstraptheme?

**Comment by Madii** [comment]
@NamelessCoder Yeah you can close ist :-) ...soon i will spend some time again in fluid dev ;-) . Don't know how you can find the time for all this Claus
