### ISSUE TITLE
Illegal strong offset 'data' in PageProvider.php

### ISSUE THREAD

**Issue by Outdoorsman** [FluidTYPO3/fluidpages#241]
In TYPO3 CMS 7.1.0 and latest development versions of FT3 extensions I right click on a page and select "Disable" from the menu to disable a page and get this...

```PHP Warning: Illegal string offset 'data' in /some_directory/public_html/typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php line 248```

If any more info would be helpful let me know, I'm not sure what else would be helpful.

**Comment by NamelessCoder** [comment]
Is this still an issue on your end, Charles? I'm unable to reproduce it locally (and it smells a lot like an earlier error that would happen when creating/deleting/renaming pages in the page tree directly).

**Comment by grimmcreative** [comment]
#1: PHP Warning: Illegal string offset 'data' in /var/www/../typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php line 240

when trying to set Rights for Pages using the Access Module.
All EXT: latest Dev.
TYPO3 6.2.12
