### ISSUE TITLE
old values in tx_fed_page_flexform 

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/fluidpages#242]
Hi,

if we change the Page Layout from one to another all old values in tx_fed_page_flexform are stored in the database and do not get removed. How can i make sure that old values are removed from this field?

Best Regards.
Tobias

**Comment by NamelessCoder** [comment]
Hi Tobias,

You can use the `lowlevel` extension - it has a small command that cleans up XML values that aren't present in the data structure. I believe there's also a scheduler task you can implement if you need to do this regularly.

Cheers,
Claus

**Comment by mithri** [comment]
Hi,

thank you for the information. But how can i get the correct flexform values in a page controller with inheritation from the root page? Do you have an example or a hint where in the documentation i have to look?

Thanks
Tobias
