### ISSUE TITLE
Enabling 'no_cache' delivers wrong page-Template

### ISSUE THREAD

**Issue by MK-42** [FluidTYPO3/fluidpages#243]
I have a quite strange issue here:

My provider extension contains multiple page templates let's say TemplateOne and TemplateTwo.

If I switch on 'no_cache' on a page that has TemplateTwo (not default Template) selected, I will get the correct - changed - template rendered. But if I log out from Backend the default TemplateOne will be rendered.

So the default Template is rendered instead of the selected one if no backendUser is logged in.

With caching enabled I sometimes manage to get the correct one into cache by viewing the frontend with backend logged in and then the correct one will stay in cache. So 'no_cache' is not the cause here but makes it clear I think.

As I have to be logged out of the Backend to get the wrong behaviour I do not know how to dig in deeper into that.

Any ideas?

**Comment by MK-42** [comment]
This is caused by
FluidTYPO3\Flux\Service\WorkspacesAwareRecordService::getWorkspaceVersionOfRecordOrRecordItself()
calling 
BackendUtility::workspaceOL($table, $copy);
which is in turn checking for
$wsid = $GLOBALS['BE_USER']->workspace;
which is null if no user is logged in and is only checked against !== 0

I don't know if this is a core bug - not checking against $wsid !== null or a Flux Bug calling BackendUtility::workspaceOL from frontend.

any hints?

**Comment by NamelessCoder** [comment]
Thanks for the details @MK-42 - implemented a fix that hopefully avoids this by completely avoiding any workspace operation if no backend user exists. This should let the workspaces aware RecordService operate in both frontend and backend to display workspace versions when a user is logged in, and then fall back to standard RecordService behavior when a BE user is not logged in.
