### ISSUE TITLE
Cannot create new pages ( 2: SQL error: 'Field 'tx_fed_page_flexform_sub' doesn't have a default value' (pages:NEW551bbb726bd380.41869622) )

### ISSUE THREAD

**Issue by pvos** [FluidTYPO3/fluidpages#244]
While trying to create new pages Im getting this issue:

2: SQL error: 'Field 'tx_fed_page_flexform_sub' doesn't have a default value' (pages:NEW551bbb726bd380.41869622)

Is this a known issue or is there a known fix?
Have found numerous posts online with this issue none address a solution though.

**Comment by bjo3rnf** [comment]
@pvos you can avoid this by disabling strict mode in MySQL.

**Comment by pvos** [comment]
Thank you bj03rnf.
I have disabled strict mode and restarted the mysql server but the problem still persist.
'Field 'tx_fed_page_flexform_sub' doesn't have a default value' 

Im unable to setup a layout for the page since it will not save with this error.
Any thoughts on how I could fix this myself?

**Comment by bjo3rnf** [comment]
Are you sure? What does ``select @@GLOBAL.sql_mode;`` return?

**Comment by pvos** [comment]
STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

**Comment by bjo3rnf** [comment]
See? It's not deactivated. ``UPDATE MODE SET @@global.sql_mode= 'NO_ENGINE_SUBSTITUTION';`` should do the trick or edit your ``my.ini`` file if applicable.

**Comment by pvos** [comment]
I managed to get it working by disabling strict mode. On OSX this seems to be a lot more work and less obvisous. Thank you for pointing out this solution, hope this helps someone else in the future!
