### ISSUE TITLE
Copying from list view bug

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidpages#245]
I'm not quite sure if this is a problem of fluidpages but I think so. All of my pages are using `Fluidpages` as Backend Layout.

I got the following problem when copying fluid content elements in the list view: 

There are 2 fluid content elements. The wrapper element is containing a `<flux:form.content name="content" />` and a simple child element which is carrying some text.
I got a page which contains the wrapper element and the child element placed in the content section of the wrapper element. 
If I switch to the list view and copy all content elements (the wrapper, and the child element) to a second page. I get three elements on the second page which is ok. (the wrapper element and its child element + the child element itself) But when I switch back to the page view the child element inside the wrapper is gone.

**Comment by coding46** [comment]
Could you please be more verbose with the three elements you got an second page. Why it is okay for you getting those?

A full minimal example of the templates you are using would be helpful again. :)

**Comment by DenisMir** [comment]
@coding46 For sure I give you more details. 

I got the setup mentioned in #246.

Here are the steps to reproduce the error: 

_Page One: Wrapper and child element page view_
![page_view_page_one](https://cloud.githubusercontent.com/assets/157281/6964021/781ddf58-d945-11e4-9c04-3efea9cbe957.png)

_Page One: Wrapper and child element in list view_
![list_view_page_one](https://cloud.githubusercontent.com/assets/157281/6964017/78186974-d945-11e4-8c82-237c85dffeec.png)

_Page One: Wrapper and child element copied in list view_
![list_view_copy_page_one](https://cloud.githubusercontent.com/assets/157281/6964018/78187284-d945-11e4-97ed-66709b88d8ee.png)

_Page Two: List view after I pasted the copied elements to the empty page_
![list_view_page_two](https://cloud.githubusercontent.com/assets/157281/6964019/78193782-d945-11e4-96e7-568dac86d947.png)

_Page Two: Switch to page view which doesn't show the child element inside the wrapper (it stays the same when I set the wrapper active)_
![missing_paragraph](https://cloud.githubusercontent.com/assets/157281/6964020/781a5810-d945-11e4-9e40-561d279c8753.png)

**Comment by DenisMir** [comment]
It works if you **only** copy the wrapper element to the new page. When you paste the wrapper element the child item gets created as well.

**Comment by DenisMir** [comment]
Ok with fluidpages 3.2.0 this bug is gone.
