### ISSUE TITLE
Custom content element icon not shown in page view

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidpages#247]
I don't know if it is even possible but it would be nice if the custom icon set to a flux form like this

```html
<flux:form id="someElement" icon="{f:uri.resource(path: 'Icons/CustomIcon.gif')}">
```

would be shown in the page view as well next to the content element. At the moment every content element gets the standard fluid icon. 

![fluid_icon](https://cloud.githubusercontent.com/assets/157281/6964373/d2eec0b6-d948-11e4-8a30-f34ae1bf481f.png)

The custom icon is only available on the content item selection page. Standard elements (non fluid) do show its custom icon.

![custom_icon_standard](https://cloud.githubusercontent.com/assets/157281/6964399/1dc4a5e2-d949-11e4-994c-a8b2adc88913.png)

It is a subtle difference but for the editor it can be very useful.

**Comment by DenisMir** [comment]
I have seen that the custom icons are now shown with fluidpages 3.2.0. 

![custom_content_icons](https://cloud.githubusercontent.com/assets/157281/7041873/8f590b7e-dddd-11e4-8649-6c9c3880f9cf.png)

Why do we need two icons now?

**Comment by NamelessCoder** [comment]
> Why do we need two icons now?

Unfortunately it is only possible to *add*, not *replace* the icon that comes from the `CType` of the record. It's the best we can do, currently.

**Comment by DenisMir** [comment]
@NamelessCoder Ok that's fine.
