### ISSUE TITLE
Conflict with version extension causing "Template could not be loaded... fluidpages/Resources/Private/Templates/Page/Index.html"

### ISSUE THREAD

**Issue by Outdoorsman** [FluidTYPO3/fluidpages#248]
I'm getting this error no matter what I do when version extension is installed or if version is installed and I do not have a BE session going in the same browser:
``` #1225709595: Template could not be loaded. I tried "/home/some_directory/public_html/typo3conf/ext/fluidpages/Resources/Private/Templates/Page/Index.html", "/home/some_directory/public_html/typo3conf/ext/fluidpages/Resources/Private/Templates/Page/index.html"```

More details:
- TYPO3 CMS 7.1
- Latest development of all FluidTYPO3 extensions
- Using fluidbootstraptheme and my own provider extension

**Comment by Outdoorsman** [comment]
```TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/home/some_directory/typo3_src-7.1.0/typo3/sysext/fluid/Classes/View/TemplateView.php in line 349.```

**Comment by Outdoorsman** [comment]
**Uninstalling the extensions workspaces & version seems to fix this issue** so something weird is going on between these extensions and FluidTYPO3. The error persisted until verion was uninstalled so I suspect that is the specific extension there the issue is with. Here's where I finally figured this out in someone else's report on the IRC logs. I spoke briefly with @coding46 about this issue today and I know that @NamelessCoder has done a fair amount of work around workspaces a likely version related stuff, so I'm just dropping your names here.

**I can also make the frontend error go away if I have a BE session going in the same browser I am viewing the frontend with** (also mentioned in the IRC logs). If there is no BE session in the current browser the error can only be fixed by uninstalling workspaces/version.

https://fluidtypo3.org/community/irc-logs.html?tx_fluidtypo3org_content%5Bdate%5D=20141217&tx_fluidtypo3org_content%5Bcontroller%5D=Content&cHash=b1b888e05d3b01bb4e9cefc8bf6aceb8#14:34:37

**Comment by Outdoorsman** [comment]
I have updated the comments above in this issue with correct info now... **please re-read it**.

**Comment by NamelessCoder** [comment]
Solved (knock on wood) via https://github.com/FluidTYPO3/flux/issues/799
