### ISSUE TITLE
Faulty XML values in pages:tx_fed_page_flexform(_sub)

### ISSUE THREAD

**Issue by philippjbauer** [FluidTYPO3/fluidpages#254]
With fluidpages 3.2.1/3.2.2 after saving page properties the following XML is saved into the fields tx_fed_page_flexform and tx_fed_page_flexform_sub fields in the database:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>

    </data>
</T3FlexForms>
```

This causes the following error when the page is opened up in the BE and FE:

    PHP Warning: array_values() expects parameter 1 to be array, string given in /typo3/sysext/extbase/Classes/Service/FlexFormService.php

After downgrading to 3.2.0 everything is working fine again and no values are saved into the mentioned fields, if no options are set in the page options panel.

I defined a flux:field.inline.fal element as a page option in my page template.

Using TYPO3 CMS 6.2.12

**Comment by bjo3rnf** [comment]
I came across this as well after clearing all values (to let them be inherited again) and then saving a form.

**Comment by bjo3rnf** [comment]
Fixed by https://github.com/FluidTYPO3/flux/pull/832
