### ISSUE TITLE
Disable parent option for subpages if siteRootInheritance is disabled

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/fluidpages#259]
If ``plugin.tx_fluidpages.siteRootInheritance = 0`` is set via TS the option "Parent decides" is only disabled for field "Page Layout - this page" (``tx_fed_page_controller_action``) but not for field "Page Layout - subpages" (``tx_fed_page_controller_action_sub``) in the page the TS template resides.

I think both ``tx_fed_page_controller_action`` and ``tx_fed_page_controller_action_sub`` must be set/must not be inherited in a site root page if inheritance is disabled.

~~~~
--- Classes/Backend/PageLayoutSelector.php	(revision 654158980ed0a6edbfb268e41be4976badeedeb2)
+++ Classes/Backend/PageLayoutSelector.php	(revision )
@@ -111,7 +111,7 @@
 		$typoScript = $this->configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
 		$settings = GeneralUtility::removeDotsFromTS((array) $typoScript['plugin.']['tx_fluidpages.']);
 		$hideInheritFieldSiteRoot = (boolean) (TRUE === isset($settings['siteRootInheritance']) ? 1 > $settings['siteRootInheritance'] : FALSE);
-		$forceDisplayInheritSiteRoot = (boolean) ('tx_fed_page_controller_action_sub' === $parameters['field']);
+		$forceDisplayInheritSiteRoot = (boolean) ('tx_fed_page_controller_action_sub' === $parameters['field'] && FALSE === $hideInheritFieldSiteRoot);
 		$forceHideInherit = (boolean) (0 === intval($parameters['row']['pid']));
 		if (FALSE === $forceHideInherit) {
 			if (FALSE === $pageIsSiteRoot || TRUE === $forceDisplayInheritSiteRoot || FALSE === $hideInheritFieldSiteRoot) {
~~~~

I have no idea what to change in function getRenderInheritanceFieldTestValues() in PageLayoutSelectorTest.

**Comment by jmverges** [comment]
Hi there,

I can confirm the behaviour and I can confirm your fix solve it. Do you mind to use our contribution guide the next time? It is quite easy: https://fluidtypo3.org/documentation/contributing/contribution-guide.html

**Comment by xf-** [comment]
fix is merged

**Comment by georg-tiefenbrunn** [comment]
Thanks for fixing this, @jmverges!
I'm aware of the contribution guide but didn't want to break the unit tests with an incomplete PR.
