### ISSUE TITLE
Forward in Custom Page Controller fails when using namespaced provider extension

### ISSUE THREAD

**Issue by moger-xx** [FluidTYPO3/fluidpages#271]
Hi,

I am using two different fluidtemplates "Standard.html" and "Test.html". Both render correctly in frontend.

Now, on a page which is using the "test" template, I want to forward from test to standard action, so that the test page is (internally) using the standardAction instead of the testAction to continue rendering 

But as soon as I use the "forward" method in a testAction in my namespaced custom pageController within my fresh provider extension, like this:
`    public function testAction() {
        $this->forward('standard');
    }`

 I always get an autoloader error:
"Could not analyse class:Tx_ConMyextension_Controller_PageController maybe not loaded or no autoloader?"

It seems that the namespaced version of the page controller class cannot be determined correctly.

Versions:
- TYPO3 6.2.14
- fluidpages 3.3.1
- flux 7.2.1
- fresh provider extension named "Constructiva.ConMyextension" built via builder 0.20

**Comment by moger-xx** [comment]
See this gist: https://gist.github.com/moger-xx/2d2a7661409888dceb32

**Comment by moger-xx** [comment]
no clues?

**Comment by NamelessCoder** [comment]
Have clues (request passed to Flux Form retrieval). Need time, though. Sorry.

**Comment by NamelessCoder** [comment]
Should be working now - vendor name was not being added to the sub-Request Flux creates. It is now :)

**Comment by moger-xx** [comment]
AWESOME! :)
