### ISSUE TITLE
page view icon is broken

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/fluidpages#272]
For my own content-element i use
```
<flux:form id="textwithimage"
				   options="{group: 'OwnContent',icon: '{f:uri.resource(path: \'Icons/icon-row-2.png\')}'}">
```
In the Creation of the Content element the icon is shown. But in the page view there is a broken image-Icon, because the image-path to the icon is wrong: ".../typo3conf/ext/fluidcontent_ownContent/Resources/Public/Icons/icon-row-2.png" which results in [domain]/typo3/sysext/cms/typo3conf/ext/fluidcontent_ownContent/Resources/Public/Icons/icon-row-2.png which cant be right.
Is this a bug or do I have to configure the page view icon somewhere else?

**Comment by xf-** [comment]
Hi,

i think you mean fluidcontent and not fluidpages. You will find a open ticket about icon issue in content wizard.
