### ISSUE TITLE
how to inherit/access page-settings between parent and sub-template?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/fluidpages#273]
I would expect any way to access and/or inherit settings of a rootpage template from within a sub-template.

Currently I don't see any way. So f.e. if I use a form file-field "logo" I must re-declare it for every template used!

There's a hack that makes it possible to retrieve settings from flexform (f.e. tx_fed_page_flexform) of another page.

But this still only is a bad workaround in my eyes and does no settings-merging and it is still limited to a FIXED uid.

This is very unflexible f.e. if you want to be able to override settings for sub-pages and if the next parent for 'tx_fed_page_flexform' is not the real rootpage (uid:1) but a child-page of it and the parent of our current sub-page (root - > sub to override some field -> current child page)

```
{flux:form.data(uid: 1, table: 'pages', field: 'tx_fed_page_flexform')-> v:variable.set(name: 'parentSettings')}
```

I think the best way would be to extend form.data with something like a slide-attribute (just like done for content-rendering in VHS).

**Comment by NamelessCoder** [comment]
You can read a bit more here about why the inheritance is at it is:

https://fluidtypo3.org/documentation/templating-manual/templating/using-templates/template-inheritance.html

In short: yes, absolutely, you have to declare the field on every template that must be able to inherit it. No data structure means no inheritance. You have to think of this as if it were TCA, except slightly more flexible in that you don't *have* to define the field everywhere - only when you want it to be inherited is that necessary.

There are numerous ways to reuse form components and even individual fields. You can even manipulate this in straight PHP by programmatically adding fields determined by parent template selections. But common for every solution is that yes, the resulting data structure must contain the field definition or it just gets ignored like it should be.

The only truly universally inheritable contexts to set such values are:

* TCA extensions for `pages` plus adding the field to root line fields.
* TypoScript

I recommend TypoScript with a constant and proper definition for the constants editor. A logo file is exactly the type of setting that should be a constant.

In general: you should be quite conservative about which fields you use when you create *page* templates. Far from every type of configuration makes sense as a page property; whether or not it is inherited. And usually, things you want to inherit are best placed in TypoScript under the `.settings` scope to make them available in controllers and templates automatically.

> I think the best way would be to extend form.data with something like a slide-attribute (just like done for content-rendering in VHS).

- We've got inheritance controls on Flux fields too and they can't be global
- We would force everyone to only use `flux:form.data` to get inheritance
- Inheritance is not a Flux feature but a Fluidpages feature added by its providers (the Flux options will be deprecated in 7.3; moved to the `options` sub-array).

So I would have to disagree that moving this to a `slide` on `flux:form.data` would be the best way. Very limited use and careful attention to the data structure of every template involved in the root line, and/or preferring (declarative) TypoScript, is the best advise I can give.
