### ISSUE TITLE
Development version doesn't work for creating pages, folders etc. on TYPO3 7.4

### ISSUE THREAD

**Issue by 4WakeStudio** [FluidTYPO3/fluidpages#275]
Hey,

I installed the development version of the fluid extensions (flux, vhs, fluidpages, fluidcontent, fluidcontent_core, builder) on my new TYPO3 7.4 installation. I built a provider extension for my site templates with the builder. When I want to create a page (or other things in the tree like folders etc.) I get following exception:

PHP Catchable Fatal Error: Argument 1 passed to FluidTYPO3\Fluidpages\Provider\PageProvider::getForm() must be of the type array, null given, called in /home/www/neu/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php on line 630 and defined in /home/www/neu/typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php line 160

When I reload the backend then the page gets created and is disabled. Without reloading I can't access the new page. The title of the new page says "Please wait...".

What should I do? Is this a known bug? I didn't find a solution.
I found a similar problem here https://github.com/FluidTYPO3/fluidpages/issues/235 but the structure of the folders etc. is different in the new version.

Would be nice if there is a solution. Thanks in advance!

**Comment by NamelessCoder** [comment]
Solved, please pull flux development again.
