### ISSUE TITLE
Access request arguments in custom PageController not possible (empty)

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidpages#277]
I have got a custom page controller which extends from `FluidTYPO3\Fluidpages\Controller\PageController`. This does work perfectly. But when I try to access the request arguments from the current request in a controller action I'm getting no result. 

Here are some examples that I've tried: 

`$this->request->getArguments()` - Result is an empty array.
`$this->request->getOriginalRequest()` - Result is a null original request object

What is the correct way of accessing the arguments?

**Comment by NamelessCoder** [comment]
Could you give an example of a set of URL parameters that fail?

What is your controller's vendor name / extension name?

**Comment by DenisMir** [comment]
Here is the situation: 

I have got a PageTemplate called `OneColumnPage` in which I have a navigation that renders some additional page links which are linked to a hidden page which contains a plugin (which renders detail view of an item) and depending on the given `item id` the correct item gets displayed. To know if the navigation link should be `active` I need to know if the current request contains a parameter named `tx_test_itemsplugin[itemId]`. I'm not quite sure if the custom `PageController` does only get the namespaced parameters or if it can access parameters from other plugins as well. (I'm not quite sure about this) But I know that the `oneColumnPageAction` gets called since I can assign additional view variables and I'm able to access them in the page template.

**Comment by NamelessCoder** [comment]
Request arguments in Extbase will always be wrapped in the `tx_signature_plugin` wrapping and the Request object in controller and other places will only contain those arguments that match the Request's own extension- and plugin name. In other words: if you've got `$_GET['tx_test_plugin']` you can only read the parameters if your Request also contains `extensionName=Test` and `pluginName=Plugin` (or, any of the alternatives that will cause automatic resolving). It's clear you're trying to access foreign request parameters here.

You're simply not supposed to be able to read the Request parameters targeted at another plugin. It's a built-in limitation of Extbase's MVC.

If you need to use page-related request arguments, define the arguments on your PageController action and access them that way. Or, manually fetch whatever you need from `$_GET` **and make sure you escape the hell out of it!**

**Comment by DenisMir** [comment]
Thank you very much for the explanation!
