### ISSUE TITLE
PageLayoutSelector values remain not prefixed by a vendor

### ISSUE THREAD

**Issue by wikipeter** [FluidTYPO3/fluidpages#280]
Hi there,

I was just wondering if this is a real issue or if it's due the fact that i'm using latest development branch [be37fc0] while NamelessCoder is "in the process" of rewriting the PageLayoutSelector values and PageService to become not prefixed by a vendor.

If the values are stored in database without a vendor prefix, PageController seems not involved in the rendering process of forntend. At least DebuggerUtility::var_dump() output is missing if i add it to some PageController action.

Anyway, [351d3c6] causes this behaviour. Previously the assignment of a page template resulted in Vendor.MyExtension->UpperCamelCase now it is MyExtension->lowerCamelCase.

Peter

**Comment by jmverges** [comment]
I can confirm there is a problem here. I'm using TYPO3 master and FluidTYPO3 development. I'm not sure where is the problem. 

To test it, I just created a Test.Test extension with ext:builder and I write in the PageController a standardAction function expecting to be able to debug the code in it when I go to the frontend. I can put breakpoints in FluidTYPO3\Fluidpages\Controller\PageController but not in Test\Test\ControllerPageController.

'Test.Test' in ext_tables, Test->standard is in pageLayoutSelector and also in database.

**Comment by jmverges** [comment]
I'm going a reopen this because I detected other behaviour: If the page has selected "parent decides" option PageController standardAction is not triggered.

**Comment by jmverges** [comment]
Well, at the moment, "parent decides" is working and I think there wasn't any commit related to this so probably it was my own mistake. Sorry guys.
