### ISSUE TITLE
Drag and Drop weird behaviour

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidpages#282]
I think a video will explain better the situation:
https://www.youtube.com/watch?v=9hD9nF-tcPQ&feature=youtu.be

Basically: when I drag and drop to a upper content area in the layout a nested content element, Content Element is not updated. I need to move it first to a lower area and then move it to the upper area again.

**Comment by mangopulp** [comment]
I have also a behavior which relates to this issue I think. I use TYPO3 Version 7.5.0 and fluidpages 3.3.1. If I drag out a content-element from a parent grid-content-element, the field "Parent Element" of the child-element doesn't get updated and the relation still exist. The difference is, that the content-elements shown separately in the backend-layout also after updating the view. They don't get nested back again. But if I cut the grid-content-element and move it to an other page, I also move the previous child content-element. A workaround could be to remove the ID in the field "Parent Element", but this field is not editable.

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/7e20161288e6a830565e288bab91e908ca196ea3
