### ISSUE TITLE
Deprecated SpriteManager

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/fluidpages#290]
fluidpages shouldn't use `\TYPO3\CMS\Backend\Sprite\SpriteManager` when running under TYPO3 7, because it's deprecated.

**Comment by smichaelsen** [comment]
https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.5/Feature-68741-IntroduceNewIconFactoryAsBaseForReplaceTheIconSkinningAPI.html

**Comment by xf-** [comment]
i can't find any notice in SpriteManager Class about deprecation and no other class has:
addTcaTypeIcon.

**Comment by smichaelsen** [comment]
SpriteManager is deprecated since https://github.com/TYPO3/TYPO3.CMS/commit/58c46d75099acd8449aded959efe8f031cec13d0

**Comment by xf-** [comment]
Thx - My fault, i was in wrong folder. PR is welcome :)

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/fluidpages/blob/development/ext_localconf.php#L41 remains. Do we need to do anything or can this be closed since we don't use SpriteManager directly?

**Comment by NamelessCoder** [comment]
Feature that used the sprite manager icon is removed so now this is definitely no longer a problem :)
