### ISSUE TITLE
tx_fed_page_flexform can not be localized

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/fluidpages#292]
All fields that are set in the flexform for a page cannot be translated. The whole field tx_fed_page_flexform and all its functions are simply missing for the pages_language_overlay table. 

I guess, this is a missing core feature of this extension and not be design. It is a common use case to have content field (like an extra subtitle) configured on the page flexform that has to be translatable.

**Comment by NamelessCoder** [comment]
This is actually by design - you can manually add the field to `pages_language_overlay`, or you can use the `translation` option for `flux:form`:

https://github.com/FluidTYPO3/flux/commit/bf3920cadc579b20226564dde94d9f2da692bd38

**Comment by mrk131324** [comment]
That's a cool, non-documented feature. But it does not work for pages, because the fields for the flexform is missing for pages_language_overlay. And this field is not so easy to add, because the flexform is not ment to be used for pages_language_overlay.
