### ISSUE TITLE
[FEATURE] Use collapsable lists for page configuration

### ISSUE THREAD

**Issue by krokodok** [FluidTYPO3/fluidpages#302]
When setting up some configuration fields for page templates it quickly becomes a great mess, especially when one uses some FAL-fields. Part of the problem is, that all the configuration is doubled for subpage configuration. It would be neat if one could collapse "page configuration" and "subpage configuration". Maybe even load the tab with both sections collapsed.

**Comment by moger-xx** [comment]
+1 for a flux option for collapsing subpage configuration by default.

**Comment by NamelessCoder** [comment]
Hi guys,

TYPO3 TCA unfortunately does not support collapsing entire FlexForm fields (although I agree that could be a nice thing). If TYPO3 supports it we can support it, but until then, the best I can do is refer you to the [TYPO3 core bug tracker](https://forge.typo3.org/projects/typo3cms-core/issues) to create a feature request there.
