### ISSUE TITLE
[ Typo3 7.6.2 + 3.4.0 ] Cannot get any page preview in the backend

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/fluidpages#303]
Everytime I visit a page I get this on the backend:

```php
Fatal error: Call to a member function setOption() on null in '/var/www/myproject/htdocs/typo3conf/ext/fluidpages/Classes/Hooks/PagePreviewRenderer.php' on line 38
```

Can you help me on understand what I missed?

The project was already a living project, upgraded from 6.2.x to 7.6.2, built with Grid Elements and static Typoscript as basic template.

So I used the `site` kickstarter extension over it and now I ended with that error. Any help is appreciated.

Thanks in advance.

**Comment by julianxhokaxhiu** [comment]
Omg I found it: backend layout was not set. Once I set it ( editing the root page and setting for that pages and all subpages ) it worked straightforward!

I'll leave this as a documentation if it's ok for you :) Sorry and thanks anyway!

**Comment by NamelessCoder** [comment]
Hi Julian,

Even so, this is an error that should either be suppressed, logged or replaced with a more specific message. I think we will suppress it, when attempting to resolve the template while rendering the BE page preview.

So thanks for reporting ;)
