### ISSUE TITLE
Page template icons not found anymore

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#309]
Icons for page templates are not found anymore; thus when editing a page record, the page templates in the "Page Layouts" have no icons anymore.

Previously, icons for page templates were looked for in `Resoures/Public/Icons/Page/Foo.png`.
Now the template file name in the page template's form object only contains the file name itself, without the `Page/` folder prefix, thus `flux\Utility\MiscellaneousUtility::getIconForTemplate()` generates the wrong icon path - `Resoures/Public/Icons//Foo.png`.

This happens with flux 7.3.0 and fluidpages 3.4.0.

It worked in fluidpages 3.3.1 when the full template path was available in the form.

![2016-01-27 fluidpages icon](https://cloud.githubusercontent.com/assets/59036/12610221/c847e234-c4e6-11e5-8bf1-de6daca651d8.png)

**Comment by b3nkai** [comment]
I reproduce the problem (TYPO3 7.6.2 / Flux 7.3.0 / Fluidpages 3.4.0)
