### ISSUE TITLE
Bypassing cache usage in PageProvider caused by wrong condition

### ISSUE THREAD

**Issue by phpManiac77** [FluidTYPO3/fluidpages#311]
In method FluidTYPO3\Fluidpages\Provider\PageProvider::getInheritedConfiguration() is a condition for checking the cache. It can happen that a cache is actually empty. If that is true there is no need to query the database if the cache key exists but it contains only an empty array.

`
//patch
--- typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php	(revision )
+++ typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php	(revision )
@@ -304,7 +304,7 @@
 		$tableName = $this->getTableName($row);
 		$tableFieldName = $this->getFieldName($row);
 		$cacheKey = $tableName . $tableFieldName . $row['uid'];
-		if (TRUE === empty(self::$cache[$cacheKey])) {
+		if (FALSE === isset(self::$cache[$cacheKey])) {
 			$tree = $this->getInheritanceTree($row);
 			$data = array();
 			foreach ($tree as $branch) {
`

**Comment by NamelessCoder** [comment]
Implemented - at least `development` branch currently contains the requested code.
