### ISSUE TITLE
improve error message "oops code..."

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidpages#312]
maybe its also a flux issue:

please improve that one line error message (oops code ..........) which comes when something goes wrong in rendering.

Yesterday i forgot some partials and i searched and searched for the reason.

**Comment by cedricziel** [comment]
That's dependant on your ExceptionHandler configured in the CMS, no fluidpages/flux issue. You should consider switching to the development context (through `TYPO3_CONTEXT`) for your local development environment.

**Comment by blueamerican** [comment]
TYPO3 7.6.4:
In the installation tool > Debug settings > Debug (former Development) is activated

**Comment by NamelessCoder** [comment]
Sorry to hear about that issue - unfortunately it is outside our control. You may want to check the TYPO3 bug tracker, it should contain some info about this (it's a general issue with View/ViewHelper errors and is as Cedric states dependent on the context).

**Comment by bjo3rnf** [comment]
@blueamerican been there, done that. As @cedricziel already mentioned make sure to set that environment variable. Enabling debug mode in install tool doesn't suffice.

**Comment by blueamerican** [comment]
ok thanks.. i'll check it

**Comment by NamelessCoder** [comment]
Imma heart the hell out of everything informative from now on!

**Comment by cedricziel** [comment]
Sorry. Does it trigger notifications? First time user here :)

**Comment by NamelessCoder** [comment]
I wasn't being sarcastic - it's great that we're now able to highlight the good stuff! If it does cause a notification I think it's only for the author... at least I didn't get one for your heart :)

**Comment by cedricziel** [comment]
Maybe @bjo3rnf can tell us since I .. played a bit with it :)

**Comment by NamelessCoder** [comment]
Heh, I know what that probably means (clickfest!)

**Comment by bjo3rnf** [comment]
What the actual eff? ^^

**Comment by NamelessCoder** [comment]
No notifications here - good! Or great!

**Comment by bjo3rnf** [comment]
There, I fixed it: ![bildschirmfoto 2016-03-11 um 13 46 07](https://cloud.githubusercontent.com/assets/1183009/13702527/a5986b34-e78f-11e5-9d9f-b3d320d91fce.png)

**Comment by blueamerican** [comment]
i only understand "Bahnhof"

**Comment by cedricziel** [comment]
Nevermind. We're just a bunch of teenagers drooling over github "reactions" :)

If you have additional questions about the contexts, don't hesitate to ask.

**Comment by blueamerican** [comment]
ah ok i thought you laughed about me:-)
