### ISSUE TITLE
Document "Raw fluid template" page type

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#320]
The page type "Raw fluid template" is not documented anywhere.

**Comment by NamelessCoder** [comment]
Feature has been removed. Essentially it would create a new "PAGE" type TS object with a custom type number that would directly render, and only render, the Fluid template that was selected - allowing an individual fluid template file to be selected in page properties. So it should hopefully be very easy to recreate, should anyone have the need for this or something similar.
