### ISSUE TITLE
Error disabling page in workspace

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#321]
In a workspace, right-clicking a page in the page tree and selecting "disable" leads to a fatal error:

> Catchable fatal error: Argument 2 passed to FluidTYPO3\Flux\Utility\RecursiveArrayUtility::mergeRecursiveOverrule() must be of the type array, null given, called in .../typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php on line 280 and defined in .../typo3conf/ext/flux/Classes/Utility/RecursiveArrayUtility.php on line 77

That problem only occurs for pages which are "fresh" in this workspace. For page records that already exist in this workspace (previous unpublished change), it does not happen:
1. Right click page in workspace, disable -> fatal error
2. Reload page tree
3. Right click page in workspace, disable -> works now

---

This happens with fluidpages git `development` 79bc7b5 on TYPO3 7.6.2:

Seems to be related to #317.

**Comment by dr2okevin** [comment]
I get the same error when i try to activate a Page in my workspace, which ist existing and disabled in live.

Flux 7.4.0, TYPO3 7.6.9
