### ISSUE TITLE
Upgrade to 3.6.1 breaks page templates having no configuration section

### ISSUE THREAD

**Issue by kitzberger** [FluidTYPO3/fluidpages#323]
I'm not sure whether it's valid or not to have page templates without a `<section name="Configuration">` but we did have that and the upgrade from 3.6.0 to 3.6.1 broke our "fallback" template that only had a single section: `<section name="Main">`

The change which is causing the exception we're experiencing now in the TYPO3 backend is this one: https://github.com/FluidTYPO3/fluidpages/commit/5d99aada16bc6d818eca4e9388d593981f71ab2b?w=1#diff-56f3f4c49f9c4d997940062ff8ba69beR207

Maybe you wanna put another if around that line?

As a workaround we introduced this section to our template:

```
    <f:section name="Configuration">
        <flux:form id="fallback" enabled="false"></flux:form>
    </f:section>
```

**Comment by NamelessCoder** [comment]
Hi @kitzberger - better late than never:

The `Configuration` section is not technically required, but not having it requires a fair amount of custom configuration. The `flux:form` however *is* required, even if you customised your way to not requiring the `Configuration` section.

There's now a specific error informing that no form was found, with a more specific error when site is in `Development` context ;)
