### ISSUE TITLE
Local cache for `RecordService` database queries

### ISSUE THREAD

**Issue by romm** [FluidTYPO3/fluidpages#340]
I've been working on performance issues that we had lately on our new application, where the main page (containing a lot of FluidContents, and handled by FluidPages) was taking 8+ seconds (!) for its first build (with all caches cleared).

Investigating a bit showed me that 200+ queries like `SELECT * FROM pages WHERE uid='xxx';` were done; that was almost half the cost of the page building time!

I decided to try to implement some local cache, so I changed a bit the function [FluidTYPO3\Flux\Service\RecordService::getSingle()](https://github.com/FluidTYPO3/flux/blob/7.4.0/Classes/Service/RecordService.php#L40-L44) just to see what would happen:

```
public function getSingle($table, $fields, $uid)
{
    $hash = sha1(serialize([$table, $fields, $uid]));

    if (!isset($this->localStorage[$hash])) {
        $connection = $this->getDatabaseConnection();
        $record = $connection->exec_SELECTgetSingleRow($fields, $table, "uid = '" . intval($uid) . "'");
        $this->localStorage[$hash] = false !== $record ? $record : null;
    }
    
    return $this->localStorage[$hash];
}
```

With that, I gained almost 4 seconds.

I'm not saying this is the solution to this issue, but I think some local cache should be considered, maybe in [FluidTYPO3\Fluidpages\Service\PageService](https://github.com/FluidTYPO3/fluidpages/blob/3.6.1/Classes/Service/PageService.php#L26)?

What're your thoughts on this topic? I'd love to help and offer a PR if I can. :-)

**Comment by NamelessCoder** [comment]
Memoizers would be nice in places where we are sure we operate on data that will not change during a request (which basically means, anything that runs in FE only). PR would be welcome!

**Comment by romm** [comment]
@NamelessCoder here you go. ;-)
