### ISSUE TITLE
PageProvider without pagesLanguageConfigurationOverlay leads to wrong behaviour

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/fluidpages#343]
In Provider\PageProvider there's this line with `$languageRef = 'l' . $GLOBALS['TSFE']->config['config']['language'];` that prevents having the page configuration available in any other language than default.

Extension configuration 'pagesLanguageConfigurationOverlay' is not set (was not available in older versions and this is an upgrade issue).

This „feature“ was introduced with #296 

```
    public function getFlexFormValuesSingle(array $row)
    {
…
        // legacy language handling, this was deprecated in TYPO3 7.6 (Deprecation: #70138 Flex form language handling)
        // this should stay here for a little while and be removed at some point in the future
        $languageRef = null;
        if ($GLOBALS['TSFE']->sys_language_uid > 0) {
            $languageRef = 'l' . $GLOBALS['TSFE']->config['config']['language'];
        }
…
```

The condition should at least contain an additional check for a set `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluidpages']['setup']['pagesLanguageConfigurationOverlay']` and only then apply changing the $languageRef (I have no 'len' section in my flexform, only 'lDEF' … and want to use the settings from the default language)

**Comment by franzkugelmann** [comment]
I can conform the behaviour and also the fix by checking for
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluidpages']['setup']['pagesLanguageConfigurationOverlay']`

**Comment by NamelessCoder** [comment]
Sounds reasonable - a pull request to add a check for that setting would be appreciated!

**Comment by NamelessCoder** [comment]
Language merging has been entirely removed and there should be no more problems in this regard.
