### ISSUE TITLE
pages_language_overlay not display on TYPO3 v 8.6

### ISSUE THREAD

**Issue by filoucrackeur** [FluidTYPO3/fluidpages#345]
Fluidpages configuration Fields pages_language_overlay are not display on TYPO3 v 8.6 because 

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    'pages_language_overlay',
    '--div--;LLL:EXT:fluidpages/Resources/Private/Language/locallang.xlf:pages.tx_fed_page_configuration,tx_fed_page_flexform,tx_fed_page_flexform_sub'
);
```

need to be moved on TCA/pages_language_overlay.php file 

cf: breaking changes 8.6

**Comment by NamelessCoder** [comment]
Confirmed - a pull request to change this would be appreciated!
