### ISSUE TITLE
Typo3 8.7.1 + flux 8.2.1 + fluidpages 4.1.0 breaks installation

### ISSUE THREAD

**Issue by geronimoooo** [FluidTYPO3/fluidpages#355]
I'm trying to get the latest version of typo3 running with flux and fluidpages but as soon as I activate fluidpages in extension manager typo3 breaks and only shows the message

> Call to undefined method FluidTYPO3\Flux\Core::addStaticTypoScript()

The message even appears on the login screen.
I'm using a blank installation without any other extension or adjustments. Flux and fluidpages are checked out from the development branch.

After commenting out the following lines in fluidpages/ext_localconf.php...

```
 if (FALSE === isset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluidpages']['setup']['autoload'])
 	|| TRUE === (boolean) $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['fluidpages']['setup']['autoload']) {
 	\FluidTYPO3\Flux\Core::addStaticTypoScript('EXT:fluidpages/Configuration/TypoScript/');
 }
```

...fluidpages can be installed and the message disappears but the page modul will get stuck loading which ends in a 504 Gateway Timeout.

Also, if I add the following lines (taken from an older version of Flux) to flux/Classes/Core.php ...

```
	/**
	 * Contains all programatically added TypoScript configuration files for auto-inclusion
	 * @var array
	 */
	private static $staticTypoScript = array();
	/**
	 * @return array
	 */
	public static function getStaticTypoScript() {
		return self::$staticTypoScript;
	}
	/**
	 * @param mixed $locationOrLocations
	 * @return void
	 */
	public static function addStaticTypoScript($locationOrLocations) {
		if (TRUE === is_array($locationOrLocations) || TRUE === $locationOrLocations instanceof \Traversable) {
			foreach ($locationOrLocations as $location) {
				self::addStaticTypoScript($location);
			}
		} else {
			if (FALSE === in_array($locationOrLocations, self::$staticTypoScript)) {
				array_push(self::$staticTypoScript, $locationOrLocations);
			}
		}
	}
```

... the Gateway Timeout appears. PHP7-FPM is causing massive cpu load before timeout.

**Comment by kristiangoos** [comment]
I'm  having absolutely the same problems under 8.7.1 LTS. Any fixes ? Seems flux and fluidpages are not working under this version. I tryied also development versions - no change.

**Comment by geronimoooo** [comment]
Nothing new from my site - I decided to use the repo Versions of Flux, Fluidpages, Fluidcontent and VHS and ignore the incompatibility message in the first place. Most things work fine except for the chkeditor so I installed the old htmlrte extension. I'm sure, namelesscoder is working on a version for the 8.7 LTS-

**Comment by grimmcreative** [comment]
Its all running in my installations.
One Thing i had todo was:

ext_tables.php
require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));

**Comment by NamelessCoder** [comment]
Fixed by recent commits.
