### ISSUE TITLE
edit site function getOption() on null page layout

### ISSUE THREAD

**Issue by VancD** [FluidTYPO3/fluidpages#356]
hi,

first of all i want to thank you for your great work!

I'm running TYPO3 with the following speccs:

TYPO3 8 LTS (8.7.1)
fluid_styled_content (8.7.0)
flux (8.2.1)
fluidpages (4.1.0) error 'fluidpages' ext is depending on 8.6.99 max.
vhs (4.2.0)
fluidcontent (5.2.0)

when i'm trying to edit a site, i get this error:

![bug](https://cloud.githubusercontent.com/assets/3532554/26253965/58d83b40-3cb5-11e7-9f41-7a73745cf83a.png)

what is the best way to provide you error information

cheers!

**Comment by VancD** [comment]
i've tested something.

When i remove "<v:content.render column="0" />" from my page template the error doesn't show up

**Comment by eckonator** [comment]
Hi, i have the same error. What have you done to fix this error?
