### ISSUE TITLE
addRootLineFields not working anymore

### ISSUE THREAD

**Issue by Kitzberger** [FluidTYPO3/fluidpages#357]
The statement to addRootLineFields isn't working properly anymore, at least for with TYPO3 8.7 LTS and development context.

Is it OK to put non-TCA things into the TCA Overrides files?

https://github.com/FluidTYPO3/fluidpages/blob/development/Configuration/TCA/Overrides/pages.php

**Comment by IngoMueller** [comment]
Thanks for the fix, Claus. Had the same issue with TYPO3 7.6 here.
