### ISSUE TITLE
Duplicate content areas since flux 8.1.0

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#358]
I'm using TYPO3 7.6.19, fluidpages 3.6.1 and flux 7.4.0/8.1.0/8.2.1.

I've got a page template with a single grid.column in it:
```
  <f:section name="Configuration">
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column colPos="0" name="main" />
        </flux:grid.row>
      </flux:grid>
    </flux:form>
  </f:section>
```

In 7.4.0 all was fine, with 8.0.1 and 8.0.2 also. Since 8.1.0, the content area is shown twice in the backend "page" module:
![2017-06-28 fluidpages flux duplicate content areas](https://user-images.githubusercontent.com/59036/27628338-099d753c-5bef-11e7-8f07-6082e85a1d36.png)

Upgrading fluidpages to 4.1.0 does not change anything.

**Comment by monosize** [comment]
Can you post the "Preview" section.

**Comment by cweiske** [comment]
I don't have any preview section in that page template.

**Comment by cweiske** [comment]
Also happens with TYPO3 7.6.23, flux 8.2.1, fluidpages 4.1.0.

**Comment by cweiske** [comment]
It seems the upper content section is rendered by flux, while the lower one is rendered by backend\View\PageLayoutView.

**Comment by cweiske** [comment]
Our `LocalConfiguration.php` had a caching configuration for `cache_runtime` - using the redis backend.

After disabling this, and thus reverting to the default `TransientMemoryBackend`, everything works as it should.

**Comment by moe2k** [comment]
I can confirm this issue with TYPO3 v7.6.31, Flux v8.2.1, fluidpages: v4.0.0.

**Comment by NamelessCoder** [comment]
@cweiske Thanks for the feedback - the intention is that "runtime" caches are never persistent, so it is not common practice to tag entries (in fact, the default implementation ignores tags altogether) which means that when caches are flushed by changes to a record, the runtime cache isn't flushed.

I assume you have a very good reason to persist the runtime cache with redis, so my only suggestion is a workaround for DataHandler which forcibly flushes the (entire) runtime cache when a record is changed. This would (should) also work around other potential issues where changing a record does not flush other runtime-cached things (and I think I remember this is used in things like root line and page repository internals).

@moe2k If your problem still exists please ping for reopening of the issue - and attach the usual relevant information (the flux:form.grid definition, whether you need to select special options in page properties, etc.). I'm unable to reproduce this...

**Comment by cweiske** [comment]
Having the runtime cache transient makes sense. Thank you for the explanation.
