### ISSUE TITLE
Page layout selector empty since 4.1.0

### ISSUE THREAD

**Issue by rsternec** [FluidTYPO3/fluidpages#362]
Since fluidpages 4.1.0 the page layout selector doesn't show any options. Until 4.0.0 I had several page layouts available to choose.

Debug console:
TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction
'No class named FluidTYPO3\Fluidpages\Backend\PageLayoutDataProvider' (67 chars)

Perhaps #344 delivered some unwanted changes?

My system:
TYPO3 7.6.20
PHP 7.0.7
fluidpages 4.1.0
flux 8.2.1

See screenshot for further details.

![pagelayout](https://user-images.githubusercontent.com/29753281/28409061-caa65b4e-6d39-11e7-84cd-5700bd3cb14f.gif)

**Comment by NamelessCoder** [comment]
* Make sure class loading works
* Make sure you've manually flushed system caches via the install tool
* Make sure you've migrated templates, if necessary, if you also upgraded Flux
* Make sure your TS paths configurations are up-to-date and use the currently accepted plural path names.

I suspect this is a simple error in the class loading so flush those caches properly and this should go away.

**Comment by rsternec** [comment]
You are right, all is working fine now.

I think it was the caching, perhaps I forgot some step on first trial.
