### ISSUE TITLE
Reduce SQL queries

### ISSUE THREAD

**Issue by morinfa** [FluidTYPO3/fluidpages#365]
TYPO3 v7.6.23
FluidPages v4.1.0

In PageController::initializeView(), call to $this->getRecord() make a first SQL request on pages tables.
Call to parent function initializeView in class AbstractFluxController will make further calls to $this->getRecord, each call generating the same SQL query.

`SELECT * FROM pages WHERE uid = 'XXX' LIMIT 1`

Is it possible to keep the result of this SQL query for the whole initializeView process ?

**Comment by NamelessCoder** [comment]
Solved a while ago; PageController will now use the already constructed array from TSFE instead of reading records.
