### ISSUE TITLE
Nested Elements cannot be translated

### ISSUE THREAD

**Issue by swissdude** [FluidTYPO3/fluidpages#369]
Hi all

First off, excuse me if this is not the right place to ask this question - but you're kinda my last resort as all other forums seem to be deserted ;)

I'm using T3 8.7.8 with flux and fluidpages - which is basically working fine.
Except for one thing: When I create a nested HTML-Element translation of elements within the wrapper fails.

I followed this post to create the nested element: http://lists.typo3.org/pipermail/typo3-dev/2015-June/049838.html

Now, when I add the wrapper to the page, add elements to the wrapper and then hit «translate» in the other language's columns, it works (means, the whole wrapper including the elements is translated).
But when I add more elements to the wrapper AFTER I translated it and then hit the «translate» button, it hangs forever.
What I realized is, that on regular translations, the wizard shows me the ID(s) of the elements that are about to be translated. With elements within the wrapper, this doesn't happen.

Below is a screenshot how the setup looks.

![fluid-wrapper](https://user-images.githubusercontent.com/2203969/32047047-19a30488-ba45-11e7-9a40-b44f45d79cd6.png)

I could (I guess) create the extra elements outside the wrapper, then translate them and after translation move it into the wrapper in the language column. But this is cumbersome to say the least.

Anybody having an idea? It might be flux/fluidpages related, but I'm not sure - and again, I apologize if this is not related to this project.

Thanks for any help!

**Comment by zoranilic** [comment]
Yes. The same at my side. I can confirm this behavior using fluidpages with flux 8.2.1 and after upgrading to latest commit from development branch. But after the upgrade to the version from development branch I get translated records only for wrapper content elements but not for child elements. Then I need to click to "translate" button for child elements and get the translating process stuck loading forever.
One more thing as info is that I don't use fluidcontent anymore after upgrading to flux  from development branch.

**Comment by NamelessCoder** [comment]
Was an issue in Flux - solved in 9.0 release.
