### ISSUE TITLE
[Issue + Potential Fix] ERROR: The option "source" is required and must not be empty

### ISSUE THREAD

**Issue by aaron-grover** [FluidTYPO3/fluidpages#371]
Hi,

I've recently upgraded my backend to typo3 8.7, and updated fluid components to the following...:
- vhs: 4.3.3
- flux: 8.2.1
- fluidpages: 4.1.0
- fluidcontent: 5.2.0
- builder: 1.2

...and I've noticed that the fluidpages extension isn't playing nice, throwing the error mentioned in the title when I try to edit a page.

I've read around and done some digging myself and found that, in 'fluidpages/Classes/Backend/PageLayoutDataProvider', the 'renderOptions' function doesn't check if GeneralUtility:getFileAbsFileName actually returns anything before trying to run MiscellaneousUtility::createIcon.

I'd suggest having GeneralUtility::getFileAbsFileName return a default icon if it would otherwise return an empty string.

I've modified the last line of GeneralUtility::getFileAbsFileName to the following:
```
    public static function getFileAbsFileName($filename, $_ = null, $_2 = null)
    {
        if ((string)$filename === '') {
            return '';
        }
        if ($_ !== null) {
            self::deprecationLog('Parameter 2 of GeneralUtility::getFileAbsFileName is obsolete and can be omitted.');
        }
        if ($_2 !== null) {
            self::deprecationLog('Parameter 3 of GeneralUtility::getFileAbsFileName is obsolete and can be omitted.');
        }

        // Extension
        if (strpos($filename, 'EXT:') === 0) {
            list($extKey, $local) = explode('/', substr($filename, 4), 2);
            $filename = '';
            if ((string)$extKey !== '' && ExtensionManagementUtility::isLoaded($extKey) && (string)$local !== '') {
                $filename = ExtensionManagementUtility::extPath($extKey) . $local;
            }
        } elseif (!static::isAbsPath($filename)) {
            // is relative. Prepended with PATH_site
            $filename = PATH_site . $filename;
        } elseif (!static::isFirstPartOfStr($filename, PATH_site)) {
            // absolute, but set to blank if not allowed
            $filename = '';
        }
        if ((string)$filename !== '' && static::validPathStr($filename)) {
            // checks backpath.
            return $filename;
        }
        return 'default-not-found';
    }
```
Only the last line has changed (from '' to 'default-not-found', as seems to already be registered in IconRegistry), and it seems to have fixed the problem.

Alternatively, a check could be put in 'renderOptions' to see if GeneralUtility:getFileAbsFileName returns anything, selecting a default should nothing be returned.

The reason I'm raising this as a bug is because it'd be useful to have this in version control for future deployments or builds of fluidpages. Alternatively, if there is something wrong with the previously mentioned extension versions, what should I change?

Cheers
Aaron

**Comment by NamelessCoder** [comment]
The problem seems to happen in the `renderOption` method - where this line is found:

```php
$thumbnail = MiscellaneousUtility::createIcon(GeneralUtility::getFileAbsFileName($thumbnail), 64, 64);
```

Unwrapping this should solve it:

```php
$thumbnail = GeneralUtility::getFileAbsFileName($thumbnail);
$thumbnail = $thumbnail ? MiscellaneousUtility::createIcon($thumbnail, 64, 64) : null;
```

This would cause the icon reference to become null in this case, which should make TYPO3 ignore the value when rendering the select box.

If you want to prepare a pull request that would be great. You probably shouldn't change this in `GeneralUtility::getFileAbsFilename` as that is part of the TYPO3 core; especially not the last part of returning an icon identifier as last resort since that's likely to break stuff in other places.

**Comment by Gregor-Agnes** [comment]
#381
