### ISSUE TITLE
whole page appears twice

### ISSUE THREAD

**Issue by matt-rein** [FluidTYPO3/fluidpages#378]
I use the current vhs, flux, fluidpage from github (developer branche), typo3 8.7.11 php 7.2.1

my Page appears twice. For testing i use a very simple template file.

template:
```
<f:layout name="Standard" />
<h2>Test</h2>
```

no problems in Backend, but if I switch to FE, I got the test headline twice

any idea's

**Comment by matt-rein** [comment]
after deleting the 'standardAction' in PageController every thing is fine

**Comment by breakone** [comment]
Hi @matt-rein,
I have the same problem. When using my own PageController with an empty method `testAction()` the whole content of the page renders twice. If I remove the `testAction()`, everything is fine. But I need the action, to add some extra information to the page.

flux and fluidpages: dev from github
typo3 8.7.15
php 7.2.1

Test.html:
```
<f:layout name="Test" />
<h2>Test</h2>
```

PageController:
```
class PageController extends \FluidTYPO3\Fluidpages\Controller\PageController {
    public function testAction() {
    }
}
```

**Comment by NamelessCoder** [comment]
Reopened - I think there's a pull request open for this as well, if you can, please help by testing if it solves the problem!

**Comment by matt-rein** [comment]
Morning @breakone,

Try the flux PR #1492.

**Comment by breakone** [comment]
@matt-rein thanks, till now everything seems to work with the PR #1492

**Comment by NamelessCoder** [comment]
Solved via PR in Flux.
