### ISSUE TITLE
Disappearing content after update (fluidpages 4.2.0, flux 9.0.0)

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/fluidpages#385]
At first I had an old value (`fluidpages__fluidpages`) for `pages:backend_layout` and the backend page preview was fine. The content element in a flux grid was visible, but when I edited this element, I got the message
> Invalid value (3809)
for colPos.

I checked in the database: the `colPos` for the content element was set to `3809`, `tx_flux_parent` was set to `38`, `tx_flux_children` was `NULL`, `tx_flux_column` was set to `accordionContent`, `backupColPos` was `-2`, `tx_flux_migrated_version` was `9.0`

Ok, then I glanced through some other issues and found the hint to change the `pages:backend_layout`.
So I did that (changed it to `fluidpages__grid`), but now the backend page preview for an element with a flux:grid is empty and I can't edit the element anymore at all … 

![screen shot 2018-07-13 at 10 42 37](https://user-images.githubusercontent.com/146727/42682008-992bdc64-8689-11e8-8dc0-02211a670383.png)

Now the database showed a completely different picture:
`colPos` was set to `-2` (?) and `backupColPos` was set to `3809` … wtf is happening here? I didn't change anything for this element or the page it's on.

What's the correct way to update your extensions without getting into trouble (that takes hours of my time to fix in any installation) every single time? Where's the README with step by step instructions what has to be changed to make it work (again)? …

**Comment by NamelessCoder** [comment]
I think you may have `gridelements` or another similar extension installed alongside this one. Flux cannot generate a negative colPos value and the fact that the correct one gets moved to another field tells me something is changing those values behind the scenes. From the field you mention, `backupColPos`, it sounds like gridelements.

If that's the case then I honestly don't know how to proceed. If another extension is hijacking what is at this point vanilla colPos values (which are just greater than usual) then I hate to say it, but that has to be a problem of whichever extension is doing that.

Flux made the switch to completely vanilla colPos values. Before this, we had a large number of overrides that were necessary to create parent/child relationships. Now we don't, so anything that overrides TYPO3 core behavior now also overrides Flux behavior (with very few exceptions).

**Comment by wazum** [comment]
OK, whatever, I stay with the old version, thanks
