### ISSUE TITLE
Translation ViewHelper within configuration section generate exception

### ISSUE THREAD

**Issue by fisruk** [FluidTYPO3/fluidpages#387]
TYPO3: 8.7 19
Fluidpages: 4.2.0
Flux: 9.0.1

**My page template:**
```
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"

     flux:schemaLocation="http://fluidtypo3.org/schemas/flux-7.0.0.xsd"
     v:schemaLocation="http://fluidtypo3.org/schemas/vhs-1.8.5.xsd">

    <f:layout name="Default" />

    <f:section name="Configuration">
        <flux:form id="default">
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column colPos="0" colspan="12" name="Content" label="{f:translate(key:'be.page.area.default')}" />
                </flux:grid.row>
            </flux:grid>
        </flux:form>
    </f:section>

    <f:section name="Content">
        <v:content.render column="0" />
    </f:section>

    <f:section name="Sidebar">
        <v:content.render column="1" />
    </f:section>
</div>
```

**Generate in backend on "Edit page properties" following error:**
```
Call to a member function getRequest() on null 

Error thrown in file
/var/www/html/vendor/typo3/cms/typo3/sysext/fluid/Classes/ViewHelpers/TranslateViewHelper.php in line 136.
```

**It looks like get getControllerContext() return NULL**
```
$request = $renderingContext->getControllerContext()->getRequest();
```

**Additional notes**
Placing translate viewhelper within content section works fine.

**Comment by NamelessCoder** [comment]
`label="LLL:be.page.area.default"` is provided as a method to give LLL references and results in not hardcoded values but proper references in various configuration generated from the template. It is quite recommended to use that instead (as there technically is no controller to use as controller context when extracting the Configuration section's metadata).

**Comment by fisruk** [comment]
That works. Thank you for the quick support.

**Comment by olinox14** [comment]
Could this be improved to return the default translation in the case getControllerContext returns null?
Or at least a more explicit error?
Because I ran in the very same issue, and before finding this thread I had a really hard time trying to understand a way to solve this...
