### ISSUE TITLE
Partial search paths maybe Wrong?

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/fluidpages#389]
Hello there,

while donig Migration work, i notived following:

We have two Provider-Extensions, one acts as Libary, the otherone is the Page's Layout.

The TypoScript loads as it sould 
(Typoscript Object-Browser)
 [partialRootPaths]
    [0] = EXT:myExt1/Resources/Private/Partials/
    [1] = EXT:myExt2/Resources/Private/Partials/

Now the Problem:

I created the Partial "Test.html" in Both exts with different Contents, but If i want to use the Partial in myExt2, it loads the Partial from myExt1.

the Partrial fom myExt2 should be loaded.

It had worked that way with Typo3 8.7 
- Flux 8.2.1
- fluidpages 4.1.0

The Current Test Setup:
Typo3 9.5
- Flux 9.1.0
- Fluidpages 4.3.0

The TypoScript Setup is the same as before.

What can cause this issue?

**Comment by MediKathi** [comment]
Hello, I peformed some more Tests:
The mentioned result for content-elements is the same. So the issue occurs in Fluidpages and Flux

[0] = EXT:dm_layout/Resources/Private/Partials/
[1] = EXT:dm_layout1/Resources/Private/Partials/

For Content and Pages the Partials are Loaded form [0] instead of [1]
I have to modify flux and fluidpages with this code snippet in `FluidTYPO3\Flux\Controller\ContentController` and `FluidTYPO3\Fluidpages\Controller\PageController` 
```php
    protected function initializeView(\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view)
    {
    	parent::initializeView($view);
        $record = $this->getRecord();
        $extensionKey = \FluidTYPO3\Flux\Utility\ExtensionNamingUtility::getExtensionKey($this->provider->getControllerExtensionKeyFromRecord($record));
        /** @var RenderingContextInterface $renderingContext */
        $renderingContext = $view->getRenderingContext();
        $renderingContext->getTemplatePaths()->fillDefaultsByPackageName($extensionKey);
                $renderingContext->getTemplatePaths()->setPartialRootPaths(
        	[
        		\TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('typo3conf/ext/dm_layout/Resources/Private/Partials/'),
        		\TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('typo3conf/ext/dm_layout1/Resources/Private/Partials/')
        	]
        );

    }
```

Putting it in my extensions has no effect, the namespaces are: `Dm\DmLayout1\Controller\PageController` and `Dm\DmLayout\Controller\ContentController`

The Provider extensions are registered like this:
```php
//dm_layout/ext_localconf.php
	\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Dm.DmLayout', 'Page');
	\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Dm.DmLayout', 'Content');

//dm_layout1/ext_localconf.php
	\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Dm.DmLayout1', 'Page');
	\FluidTYPO3\Flux\Core::registerProviderExtensionKey('Dm.DmLayout1', 'Content');
```

The reason for the two provider extensions is, that we want a libary to store all generic content-elements and multiple extensions for the the page Layouts.

**Comment by NamelessCoder** [comment]
Explanation and workaround strategy described on https://github.com/FluidTYPO3/flux/issues/1695#issuecomment-540522695 - closing the issue here.
