### ISSUE TITLE
TYPO3 9.5.1 and a new provider extension set-up with builder causes php error

### ISSUE THREAD

**Issue by AlexanderKoe** [FluidTYPO3/fluidpages#395]
Hello guys,
fluidpages and flux are stated as "stable" and valid for TYPO3 9 LTS in extension repository, is this true?

With TYPO3 9.5.1 and a new provider extension created with "builder" causes a php error in backend at the moment the Template is selected in page editing (backend-layout is "Fluidpages"). This is a created example provider extension from builder without further configuration:

![1](https://user-images.githubusercontent.com/25105499/48271561-e1aa3880-e43c-11e8-9bbe-ddbbdbfab680.jpg)

![2](https://user-images.githubusercontent.com/25105499/48271633-0bfbf600-e43d-11e8-9ee2-348a0e1550fa.jpg)

A simple change in PageProvider.php helped me to quit this error and got the page template in backend working (2 column template):

```
// changed this $controllerActionName{0} = strtolower($controllerActionName{0}); to this:
$controllerActionName = strtolower($controllerActionName);

```
![3](https://user-images.githubusercontent.com/25105499/48271949-c855bc00-e43d-11e8-857c-5d463fed3ad3.jpg)

unfortunatelly frontend runs into 502 after 300 seconds with unchanged and changed PageProvider.php

flux | 9.1.0
fluidpages | 4.3.0

**Comment by koelll** [comment]
> causes a php error in backend at the moment the Template is selected in page editing (backend-layout is "Fluidpages")

I can't reproduce your issue, using the same versions as you, tho installed with composer and using the development version of the builder.

**Comment by AlexanderKoe** [comment]
Meanwhile I went back to TYPO3 8.7, and flux 8.2.1. Now the "builded" Extension Template works fine.
Are you interested in a deeper analysation of the problem, so I can setup a copy again with TYPO3 9 for testing...
