### ISSUE TITLE
Typo3 9.5.1 + Fluidpages 4.3.0 + DB Check

### ISSUE THREAD

**Issue by Terminator81** [FluidTYPO3/fluidpages#400]
Hi,

i have deleted some side with some sides below. Then i tried to run a db check .....that error comes:

`Argument 1 passed to FluidTYPO3\Flux\Provider\AbstractProvider::getParentFieldName() must be of the type array, null given, called in ..../typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php on line 421`

**Comment by JPDesign** [comment]
Hi Terminator 81
I have the same error message. After setting the affected page active, the error message was gone. Setup: TYPO3 8.7.22, flux 8.2.1, fluidpages 4.1.0, php 7.1.23

**Comment by mithri** [comment]
Same problem here. It happens if the parent page is disabled.
