### ISSUE TITLE
[BUG] Page Language Overlay - TYPO3 8.7.22

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/fluidpages#403]
TYPO3 8.7.22
Fluidpages 4.2.0
Flux 9.0.1
VHS 5.0.1

Error when creating a page_language_overlay of a site:

`#1463826960: TCA misconfiguration in table "pages_language_overlay" field "tx_fed_page_flexform" config section: The field is configured as type="flex" and no "ds_pointerField" is defined and "ds" is not an array. Either configure a default data structure in ['ds']['default'] or add a "ds_pointerField" lookup mechanism that specifies the data structure`

**Comment by grimmcreative** [comment]
After that Language Overlay is shown in Backend and Frontend but i can not access Page Properties. Same Error is shown.

**Comment by grimmcreative** [comment]
Same with Fluidpages 4.3.0, FLUX 9.1.0, VHS 5.1.0

**Comment by grimmcreative** [comment]
After some work - clearing caches - update everything and so on. Dont get this Error again.
------
BUT: How can i access my FLUX Configuration in translated Pages?
There is no TAB for PAGE CONFIGURATION visible.

Thanks.

**Comment by grimmcreative** [comment]
Activate: 
```
Enable translation of Page Configuration through the Pages Language Overlays.
basic.pagesLanguageConfigurationOverlay (boolean)
```
Cleared all Caches again - Error Message comes again. Can not access Page Configuration.

**Comment by grimmcreative** [comment]
Have tried Solution from this Pull Request: https://github.com/FluidTYPO3/fluidpages/pull/372/commits/95238530f7794b44bcc93cf2f288f414a8efd2fd

1. No more Errors. 
2. Page Configuration can be open.
3. Page Configuration Tab is visible.

**Comment by grimmcreative** [comment]
`<flux:field.input ... />` values of different language not get rendered via `<flux:form.data table="pages" field="tx_fed_page_flexform" uid="{page.uid}" as="pageConfig">`
:(

**Comment by NamelessCoder** [comment]
TCA part of issue solved in https://github.com/FluidTYPO3/fluidpages/commit/51f57de1284c445b1e18ce55ce376139dbaf514e, the data-values translation will be taken care of in https://github.com/FluidTYPO3/flux/issues/1661.
