### ISSUE TITLE
UnknownClassException

### ISSUE THREAD

**Issue by alandolsi** [FluidTYPO3/fluidpages#414]
(1/2) #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException
Class FluidTYPO3\typo3_template\Controller\PageController does not exist. Reflection failed.
(2/2) #-1 ReflectionException
Class FluidTYPO3\typo3_template\Controller\PageController does not exist

the problem appears only on subpages, i can't find the error, why is he looking for the namespace FluidTYPO3\typo3_template even though my namespace is different?

**Comment by alandolsi** [comment]
Problem resolved

**Comment by dipakCrayon** [comment]
how to resolved ?

**Comment by alandolsi** [comment]
the Solution for me was to rename the default Template from Default.html to Standard.html, you can not take a template with the name Default..

**Comment by dipakCrayon** [comment]
Thanks for your replay. I resolved problem by extension reinstall,because default controller was not loaded in typo3conf/autoload/autoload_classmap.php.
