### ISSUE TITLE
TYPO3 9.5.17: Error when Update reference index

### ISSUE THREAD

**Issue by enilee** [FluidTYPO3/fluidpages#418]
Hello at all,

I use:

fluidpages | 5.0.0
TYPO3 Version	9.5.17
Webserver	Apache
PHP Version	7.3.14
Database (Default)	MySQL 5.7.29
Application Context	Production
Composer mode	Enabled
Operating System	Linux 4.19.114+52-ph

I have the same problem like this issue: https://github.com/FluidTYPO3/fluidpages/issues/409
When I start update the reference index, I get the following error message after a short time:

`#1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Page->default" in format ".html", but none of the paths contained the expected template file (). The following paths were checked: /typo3conf/ext/fluidpages/Resources/Private/Templates/`

Is there still a mistake?

Thanks in advance Dennis

**Comment by NamelessCoder** [comment]
Hi Dennis,

Consider switching away from the obsolete Fluidpages to use only Flux. This problem shouldn't exist there.

**Comment by enilee** [comment]
Okay thx.
Best regards
