### ISSUE TITLE
fluidpages for Typo3 10 LTS

### ISSUE THREAD

**Issue by abohntek** [FluidTYPO3/fluidpages#419]
Hey,

will there be a release for Typo3 10.4.x coming? Or is it going to be obsolete für Typo3 10 and it has to be migrated within flux 9?

best regards,

**Comment by anglee72** [comment]
Hi I just see your question ... as far as I heard, it is obsolete. And I also heard, that you can just more or less remove the extension and flux will handle the page layout settings itself ... you may just try it with latest dev branch ...

**Comment by anglee72** [comment]
The latest Flux version also creates a directory called _design_ at the fileadmin level ... I guess that page layouts will be handled there in the future ... but I don't now.

**Comment by dogawaf** [comment]
You can actually read "OBSOLETE - functionality now served by Flux" on the [README](https://github.com/FluidTYPO3/fluidpages/blob/development/README.md)

**Comment by NamelessCoder** [comment]
Yes, EXT:fluidpages is now obsolete and the functionality is handled by EXT:flux. A migration script is included in Flux 9.4+.

The `design` folder at root level (not fileadmin) is optional and doesn't have to be used, provider extensions still work the same way. The `design` folder is intended to allow templating without the need for a provider extension.
