### ISSUE TITLE
Setting locallangXMLOverride doesn't work

### ISSUE THREAD

**Issue by ghost** [FluidTYPO3/fluidpages#86]
If I want to override the language file like this: 

```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:fluidpages/Resources/Private/Language/locallang.xlf'][] = 'fileadmin/translation/de.xlf';
```

it doesn't work. instead i have to use the full path with LLL.

any chance to get this working?

**Comment by vdoria** [comment]
@ghost
> $GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:felogin/pi1/locallang.xlf'][] = 'fileadmin/translation/de.xlf';

That's imho not the wanted/excepted behavior!? You just overwrite the default (English) language with the German one.

There is imho a extra (language) array key for XLF translations and they don't get loaded like the default one (the one you just overwrote with German strings). Just facing the same problem in 6.2
